baserepo = "tgstation/tgstation"
targetrepo = "SunsetStation/SunsetStation"
githubtoken = "placeholder token"
repoloc = "D:/Code/Rust/SunsetStation"
mainbranch = "master"
branchprefix = "upstream-merge-"